[project]
name = "xor-nn"
version = "0.1.0"
description = "Simple learning project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "numpy>=2.2.6",
    "torch>=2.7.0",
]
